spring:
  application:
  name: catalog-service
  data:
    mongodb:
      username: root
      password: toor
      uri: mongodb://localhost:27017/commerce
      auto-index-creation: false
server:
  port: 18080