version: '3.8'

networks:
  development:
    name: development

volumes:
  mysql_home:

mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:lts
    restart: always
    environment:
      MYSQL_DATABASE: 'fullstack'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - 3306:3306
    volumes:
      - mysql_home:/var/lib/mysql
    networks:
      - development
